// <auto-generated />
using System;
using IRAAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IRAAPI.Migrations
{
    [DbContext(typeof(IRAAPIContext))]
    [Migration("20201129132924_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("IRAAPI.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Announcement1")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("announcement");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<bool>("Read")
                        .HasColumnType("bit")
                        .HasColumnName("read");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("IRAAPI.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("status")
                        .IsFixedLength(true);

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("IRAAPI.Models.ChallanChargesAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<int>("ChallanId")
                        .HasColumnType("int")
                        .HasColumnName("challan_id");

                    b.Property<int>("ChargesId")
                        .HasColumnType("int")
                        .HasColumnName("charges_id");

                    b.HasKey("Id");

                    b.HasIndex("ChallanId");

                    b.HasIndex("ChargesId");

                    b.ToTable("Challan_Charges_Allocation");
                });

            modelBuilder.Entity("IRAAPI.Models.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("ChargesName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("charges_name");

                    b.HasKey("Id");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("IRAAPI.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("class_name");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("section");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("IRAAPI.Models.ClassSubjectAlloc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Class_Subject_Alloc");
                });

            modelBuilder.Entity("IRAAPI.Models.Diary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<string>("DiaryContent")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("diary_content");

                    b.Property<DateTime>("DiaryDate")
                        .HasColumnType("date")
                        .HasColumnName("diary_date");

                    b.Property<string>("DiaryTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("diary_title");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Diary");
                });

            modelBuilder.Entity("IRAAPI.Models.FeeChallan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Fee_Challan");
                });

            modelBuilder.Entity("IRAAPI.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("GradeDate")
                        .HasColumnType("date")
                        .HasColumnName("grade_date");

                    b.Property<string>("GradeTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("grade_title");

                    b.Property<int>("GradeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("grade_type_id");

                    b.Property<int>("ObtainedMarks")
                        .HasColumnType("int")
                        .HasColumnName("obtained_marks");

                    b.Property<string>("Remarks")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("remarks");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int")
                        .HasColumnName("total_marks");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("GradeTypeId");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("IRAAPI.Models.GradeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("GradeType1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("grade_type");

                    b.Property<string>("GradeTypeSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("grade_type_slug");

                    b.HasKey("Id");

                    b.ToTable("Grade_Types");
                });

            modelBuilder.Entity("IRAAPI.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Cnic")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cnic");

                    b.Property<string>("ContactPrimary")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contact_primary");

                    b.Property<string>("ContactSecondary")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contact_secondary");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("first_name");

                    b.Property<string>("JobAddress")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("job_address");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("last_name");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("occupation");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("profile_picture");

                    b.HasKey("Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("IRAAPI.Models.ParentLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Cnic")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cnic");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("password");

                    b.Property<string>("SqAnswer")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sq_answer");

                    b.Property<int?>("SqId")
                        .HasColumnType("int")
                        .HasColumnName("sq_id");

                    b.HasKey("Id");

                    b.HasIndex("SqId");

                    b.ToTable("Parent_Login");
                });

            modelBuilder.Entity("IRAAPI.Models.SecurityQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.ToTable("Security_Questions");
                });

            modelBuilder.Entity("IRAAPI.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("SessionYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("session_year");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("IRAAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollment_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("last_name");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("profile_picture");

                    b.Property<string>("RollNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("roll_no");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("IRAAPI.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("subject_code");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("subject_name");

                    b.Property<string>("SubjectSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("subject_slug");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("IRAAPI.Models.SubjectGradeTypeAlloc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("GradeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("grade_type_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("GradeTypeId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Subject_GradeType_Alloc");
                });

            modelBuilder.Entity("IRAAPI.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Cnic")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cnic");

                    b.Property<string>("ContactPrimary")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contact_primary");

                    b.Property<string>("ContactSecondary")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contact_secondary");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("joining_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("last_name");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("profile_picture");

                    b.Property<int?>("Salary")
                        .HasColumnType("int")
                        .HasColumnName("salary");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("specialization");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("IRAAPI.Models.TeacherSubjectAlloc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Teacher_Subject_Alloc");
                });

            modelBuilder.Entity("IRAAPI.Models.Announcement", b =>
                {
                    b.HasOne("IRAAPI.Models.Class", "Class")
                        .WithMany("Announcements")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Table_Classes");

                    b.HasOne("IRAAPI.Models.Session", "Session")
                        .WithMany("Announcements")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK_Table_Sessions")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Student", "Student")
                        .WithMany("Announcements")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_Table_Students");

                    b.Navigation("Class");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IRAAPI.Models.Attendance", b =>
                {
                    b.HasOne("IRAAPI.Models.Class", "Class")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Attendance_Classes")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Session", "Session")
                        .WithMany("Attendances")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK_Attendance_Sessions")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_Attendance_Students")
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IRAAPI.Models.ChallanChargesAllocation", b =>
                {
                    b.HasOne("IRAAPI.Models.FeeChallan", "Challan")
                        .WithMany("ChallanChargesAllocations")
                        .HasForeignKey("ChallanId")
                        .HasConstraintName("FK_Challan_Charges_Alocation_Fee_Challan")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Charge", "Charges")
                        .WithMany("ChallanChargesAllocations")
                        .HasForeignKey("ChargesId")
                        .HasConstraintName("FK_Challan_Charges_Alocation_Charges")
                        .IsRequired();

                    b.Navigation("Challan");

                    b.Navigation("Charges");
                });

            modelBuilder.Entity("IRAAPI.Models.ClassSubjectAlloc", b =>
                {
                    b.HasOne("IRAAPI.Models.Class", "Class")
                        .WithMany("ClassSubjectAllocs")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Class_Subject_Alloc_Classes")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Subject", "Subject")
                        .WithMany("ClassSubjectAllocs")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK_Class_Subject_Alloc_Subjects")
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("IRAAPI.Models.Diary", b =>
                {
                    b.HasOne("IRAAPI.Models.Class", "Class")
                        .WithMany("Diaries")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Diary_Classes")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Session", "Session")
                        .WithMany("Diaries")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK_Diary_Sessions")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Subject", "Subject")
                        .WithMany("Diaries")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK_Diary_Subjects")
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Session");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("IRAAPI.Models.FeeChallan", b =>
                {
                    b.HasOne("IRAAPI.Models.Student", "Student")
                        .WithMany("FeeChallans")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_Fee_Challan_Students")
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IRAAPI.Models.Grade", b =>
                {
                    b.HasOne("IRAAPI.Models.Class", "Class")
                        .WithMany("Grades")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Grades_Classes")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.GradeType", "GradeType")
                        .WithMany("Grades")
                        .HasForeignKey("GradeTypeId")
                        .HasConstraintName("FK_Grades_Grade_Types")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Session", "Session")
                        .WithMany("Grades")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK_Grades_Sessions")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_Grades_Students")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK_Grades_Subjects")
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("GradeType");

                    b.Navigation("Session");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("IRAAPI.Models.ParentLogin", b =>
                {
                    b.HasOne("IRAAPI.Models.SecurityQuestion", "Sq")
                        .WithMany("ParentLogins")
                        .HasForeignKey("SqId")
                        .HasConstraintName("FK_Parent_Login_Security_Questions");

                    b.Navigation("Sq");
                });

            modelBuilder.Entity("IRAAPI.Models.Student", b =>
                {
                    b.HasOne("IRAAPI.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Students_Classes")
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("IRAAPI.Models.SubjectGradeTypeAlloc", b =>
                {
                    b.HasOne("IRAAPI.Models.Class", "Class")
                        .WithMany("SubjectGradeTypeAllocs")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Subject_GradeType_Alloc_Classes")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.GradeType", "GradeType")
                        .WithMany("SubjectGradeTypeAllocs")
                        .HasForeignKey("GradeTypeId")
                        .HasConstraintName("FK_Subject_GradeType_Alloc_Grade_Types")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Subject", "Subject")
                        .WithMany("SubjectGradeTypeAllocs")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK_Subject_GradeType_Alloc_Subjects")
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("GradeType");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("IRAAPI.Models.TeacherSubjectAlloc", b =>
                {
                    b.HasOne("IRAAPI.Models.Class", "Class")
                        .WithMany("TeacherSubjectAllocs")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Teacher_Subject_Alloc_Classes")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Subject", "Subject")
                        .WithMany("TeacherSubjectAllocs")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK_Teacher_Subject_Alloc_Subjects")
                        .IsRequired();

                    b.HasOne("IRAAPI.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjectAllocs")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_Teacher_Subject_Alloc_Teachers")
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("IRAAPI.Models.Charge", b =>
                {
                    b.Navigation("ChallanChargesAllocations");
                });

            modelBuilder.Entity("IRAAPI.Models.Class", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Attendances");

                    b.Navigation("ClassSubjectAllocs");

                    b.Navigation("Diaries");

                    b.Navigation("Grades");

                    b.Navigation("Students");

                    b.Navigation("SubjectGradeTypeAllocs");

                    b.Navigation("TeacherSubjectAllocs");
                });

            modelBuilder.Entity("IRAAPI.Models.FeeChallan", b =>
                {
                    b.Navigation("ChallanChargesAllocations");
                });

            modelBuilder.Entity("IRAAPI.Models.GradeType", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("SubjectGradeTypeAllocs");
                });

            modelBuilder.Entity("IRAAPI.Models.SecurityQuestion", b =>
                {
                    b.Navigation("ParentLogins");
                });

            modelBuilder.Entity("IRAAPI.Models.Session", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Attendances");

                    b.Navigation("Diaries");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("IRAAPI.Models.Student", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Attendances");

                    b.Navigation("FeeChallans");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("IRAAPI.Models.Subject", b =>
                {
                    b.Navigation("ClassSubjectAllocs");

                    b.Navigation("Diaries");

                    b.Navigation("Grades");

                    b.Navigation("SubjectGradeTypeAllocs");

                    b.Navigation("TeacherSubjectAllocs");
                });

            modelBuilder.Entity("IRAAPI.Models.Teacher", b =>
                {
                    b.Navigation("TeacherSubjectAllocs");
                });
#pragma warning restore 612, 618
        }
    }
}
